### ISSUE TITLE
EOL for Node version (10) - Fix needed urgently

### ISSUE THREAD

**Issue by SWarnberg** [oscarvantol/azure-pipelines-version-increment#6]
This task is now giving the this warning in the pipelines.

##[warning]Task 'Version Increment Task' version 0 (version-increment-task@0) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance

**Comment by oscarvantol** [comment]
Thx, I'll pick it up soon and let you know when it is there.

**Comment by oscarvantol** [comment]
Can you check if you update to 'version-increment-task@2' in your pipeline everything works for you and the warning is gone?

**Comment by SWarnberg** [comment]
Thanks @oscarvantol, I didn't know about that version. I can confirm that it works.

**Comment by oscarvantol** [comment]
Great! The version was not there until yesterday ;)
